### ISSUE TITLE
New feature: range

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-variability#126]
This would be on the Mean & Median screen

Ideas is to display range above the median brackets that are on the dot plot, as well as in the list on the left side of the dot plot accordion box.

**Comment by amanda-phet** [comment]
@catherinecarter what do you think?

**Comment by catherinecarter** [comment]
I'll mock it up and see what we think :)

**Comment by catherinecarter** [comment]
Two initial options (could be more after discussion) - both on the Spread screen since Range is a measure of spread. We can discuss in design meeting.

Option 1: A fourth option in the radio button group
![Screenshot 2023-04-21 at 10 52 02 AM](https://user-images.githubusercontent.com/109630002/233692110-19859844-5ac6-4657-9409-f08d345b5ab8.png)

Option 2: Have a toggle on the dot/line plot to show range
![Screenshot 2023-04-21 at 10 52 09 AM](https://user-images.githubusercontent.com/109630002/233692131-3ae2dd1b-b77d-4b09-a33b-b3793dbcdac3.png)

**Comment by samreid** [comment]
I feel that putting "Range" in the top one kind of takes away from the "Make up your own measure of variability" idea (which we previously favored), and makes it seem like there are just 3 choices and you can show or not show each one.  But others in today's design meeting seemed excited about just putting it in the top one and having 3 choices, so I'd like to hear more about that.

**Comment by amanda-phet** [comment]
>I feel that putting "Range" in the top one kind of takes away from the "Make up your own measure of variability" idea (which we previously favored), and makes it seem like there are just 3 choices and you can show or not show each one. But others in today's design meeting seemed excited about just putting it in the top one and having 3 choices, so I'd like to hear more about that. We kind of ran out of time for discussion.

I agree Sam.. that does feel like a limitation of having it as one of the three options. 

I do think it should be on this screen though, and not the Mean & Median screen. 

Should we go back to considering an option that shows no dot plot/measure of spread? So upon arriving to this screen, there is no measure of spread being mentioned at all?

**Comment by catherinecarter** [comment]
I'm on the fence about it. On the one hand, the previous screens have a dotplot with the opportunity to explore the median and the mean or not. But there isn't a dotplot with no functionality on it at all. So having a dotplot with no exploratory measure of center or spread seems like it might be odd to users (can flag for interviews?). At the same time, since there is some sort of "prediction" opportunity (even if we don't call it that), it makes sense to be able to freely explore. Let's talk about it on Thursday.

**Comment by samreid** [comment]
In today's meeting, we agreed we will just have the 3 radio buttons.
