### ISSUE TITLE
Support dynamic strings + layout

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#147]
While working on https://github.com/phetsims/center-and-variability/issues/77, I discovered the sim does not use any stringProperty and does not change during ?stringTest=dynamic. This is typically a lot of work to implement. 5+ story points.

**Comment by marlitas** [comment]
We should wait till https://github.com/phetsims/center-and-variability/issues/206 is complete to finalize this work.

**Comment by marlitas** [comment]
The sim is in a really good condition for dynamic strings. I only found the one buggy case above. There are some situations where we could maybe fine tune the maxWidths. I created a separate issue for those pixel polishes. 

I think this is ready to close since the larger past commits are probably stale at this point.
