### ISSUE TITLE
Move median arrow node from the sceneView to the screenView

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#197]
We saw that most things are in the screen, and would like to move the median arrow node there as well.

**Comment by samreid** [comment]
I moved it from the scene view to the screen view, @marlitas or @matthew-blackman can you please review/test?

**Comment by marlitas** [comment]
Code looks good, and I like it better in the ScreenView. It seems to be functioning properly with some basic testing. The one thing that looked a little off to me was the distance between the medianArrow and the top most stacked ball. It seems like there is too much of a margin there. But may be a design/pixel polish question. May want to track that in a different issue. 

Otherwise I'm ready to close.

**Comment by marlitas** [comment]
I was not looking at the most up to date commit when I posted that. So sorry. The positioning gap no longer exists, but it does seem like it's too close now? 

<img width="360" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/bd322a7e-23e8-4acb-a6a6-02d7ec3dd891">

**Comment by marlitas** [comment]
Closing this as completed. Pixel polishes being addressed here: https://github.com/phetsims/center-and-variability/issues/146

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by marlitas** [comment]
TODO addressed. Thanks phet-dev bot!
