### ISSUE TITLE
Eraser Button Sounds

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/center-and-variability#251]
I have this sound. [In this folder.](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?id=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FMeet%20in%20the%20Middle%20HTML5%20%28Suite%29%2FCenter%20and%20Variability%20HTML5%2FSounds&viewid=3aa550f4%2Df9ef%2D4871%2Dbcb3%2Da192486a9aaa) 

- cvEraserOptions001.mp3

It is at a pretty loud volume and its a little grating. So please put it in at 30% volume.

**Comment by samreid** [comment]
@marlitas or @matthew-blackman would you like to add this sound?

**Comment by matthew-blackman** [comment]
I can give this a shot!

**Comment by matthew-blackman** [comment]
Sound is in for the eraser, and the button now selects between a normal button press and the eraser sound based on whether there is data to erase in the current scene. Ready for your review @samreid.

Rather than implementing this with a custom button factory similar to PlayAreaCheckboxFactory, it seemed reasonable to pass nullSoundPlayer into the erase button, and choose between eraserSoundPlayer and pushButtonSoundPlayer in the button listener. Let me know if this is okay or if I should implement a similar pattern as PlayAreaCheckboxFactory.

**Comment by matthew-blackman** [comment]
Updated! Ready for your review @catherinecarter. Feel free to close if all looks/sounds good.

**Comment by samreid** [comment]
We reviewed this sound effect today, and discussed whether the eraser button should be disabled on startup.

@samreid said maybe it would be a better user experience for the reset all button to be disabled on startup, or when the sim is already in its default configuration.  But that is not how most of our sims work.
@marlitas indicated that it can sometimes be confusing when something is disabled and it is unclear how to enabled it.
@matthew-blackman points out that having the reset button enabled when an unseen scene is not in the default configuration could be confusing.

Therefore, we conclude we would like the eraser button to always be enabled, like the reset all button.  Closing.
