### ISSUE TITLE
Should be able to use keyboard to translate the interval tool

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#270]
When looking at https://github.com/phetsims/center-and-variability/issues/236, it came up that the interval tool is currently not focusable or moveable via keyboard. @samreid pointed out that according to PhET's accessible design philosophy, any interactions with mouse should also be possible via keyboard controls. Let's implement this!

**Comment by samreid** [comment]
Implemented above and works will with arrow keys and shift+arrow keys.  Code review would be nice though. Same problems as described in https://github.com/phetsims/center-and-variability/issues/302#issuecomment-1601907127

**Comment by marlitas** [comment]
Should the highlight area when shifting go to the top of the accordionBox? Looks a bit strange since the intervalTool ends below that.
<img width="494" alt="Screenshot 2023-06-23 at 2 11 14 PM" src="https://github.com/phetsims/center-and-variability/assets/42476338/281b6ded-4e71-4d8c-945b-203f7edd272c">

<img width="494" alt="Screenshot 2023-06-23 at 2 13 02 PM" src="https://github.com/phetsims/center-and-variability/assets/42476338/0934a959-bee7-40c0-b446-b7ea2eac8cc3">

It also seems odd to me that we have to declare drag behavior twice... once for keyboard input, and another for mouse input. Seems like there's probably a better approach. Let's chat about it synchronously.

**Comment by marlitas** [comment]
After checking in with @zepumph we discovered that the double dragging function (one for keyboard and one for mouse), is very common throughout the codebase (https://github.com/phetsims/scenery/issues/1238). We decided to factor out those functions in our usage and otherwise leave it as is. 

The interval tool node is getting expanded upwards in the accordion box, so "Should the highlight area when shifting go to the top of the accordionBox?" is no longer a concern.

We are ready to close.
