### ISSUE TITLE
Update cueing arrow in play area around soccer balls

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#274]
Similar to #273, interviews revealed the cueing arrow was unclear in terms of its functionality.

For all screens, let's move the cueing arrow down so it appears on either side of the ball. The arrow will appear on/around the last ball kicked since that’s likely the ball the student will be watching.
![image](https://github.com/phetsims/center-and-variability/assets/109630002/d8f54416-b05a-46da-8531-84bb71acbaf5)
![image](https://github.com/phetsims/center-and-variability/assets/109630002/c92e9cba-2325-4fc7-86cc-7cbbd162d2fc)

**Comment by samreid** [comment]
I'll take a look at this one

**Comment by samreid** [comment]
After the commit, it looks like this:

<img width="320" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/e4c6620c-b046-4265-be6a-13c4cb727d03">

Please do not worry about the incorrect indicator over the cards, it will be changed in #273 

<img width="114" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/0cc96bf3-4933-4af9-b948-9278e3e704e5">

Also, I am not too worried about the exact location of the drag indicator when the accordion box is showing, we will be changing the question bar and grass height, and can fine tune that margin afterwards:

<img width="1070" alt="image" src="https://github.com/phetsims/center-and-variability/assets/679486/cfddb358-2da7-412a-8156-e2c6367225f5">

Other than those caveats, this issue is ready for code review and design review.

**Comment by catherinecarter** [comment]
Looks great!

**Comment by marlitas** [comment]
Commit looks great and this is working well. Thanks @samreid!

Closing.
