### ISSUE TITLE
Preferences dialog to be updated 

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#275]
Looking at some other sims, the checkboxes need to be updated to a radio button group and a toggle, and the max kicks option needs to be moved higher in the list. 
![image](https://github.com/phetsims/center-and-variability/assets/109630002/7d50149c-f158-4957-bcca-2b9b4698a17e)

**Comment by amanda-phet** [comment]
Is there a reason for using radio buttons instead of a combobox for max
number of kicks? And I'm also curious why the radio buttons for plot type
are horizontal.

I recall that the UI components are in line with the title, so I think the
max kicks should have a combo box in line with the title, unless there is a
good reason to not do that.

**Comment by samreid** [comment]
Let's confirm the design with @catherinecarter before starting development.

**Comment by catherinecarter** [comment]
@amanda-phet - In design meeting last week, we looked at a couple options for the preferences dialog. 

In interviews, neither student clicked the drop down menu or realized what it was. One student went to the simulation tab in preferences, read, "Oh! Max kicks" out loud, but didn't pull the menu down. I asked her how she might change the maximum number of kicks, and after being prompted, pulled the menu down and noticed there were other options. She was surprised to see what the arrow for the combobox did.

Since there are only four choices, I thought having a radio button group instead would be more clear. Following calculus grapher, I noticed some options were horizontal and come vertical. 

![Image](https://github.com/phetsims/center-and-variability/assets/109630002/f874d572-7b1d-4b4a-a526-62a7c8f96852)

Here are the options from the design meeting we looked at, would love your feedback if you have any, although since you're not technically working, obviously only if you feel like it :)

Option 1:

![Image](https://github.com/phetsims/center-and-variability/assets/109630002/4c8bf6da-d318-4c0a-a934-b2e650d4fd6f)

Option 2 (the one we chose):

![Image](https://github.com/phetsims/center-and-variability/assets/109630002/c3f894a8-69b8-437e-9931-dd6559ff65e0)

**Comment by catherinecarter** [comment]
We could also make the plot type a vertical radio button group?


![Image](https://github.com/phetsims/center-and-variability/assets/109630002/cbb2f3f8-8fcd-476c-8b8e-0ff4a3fcccf5)

**Comment by catherinecarter** [comment]
This makes more sense, with four options:
<img width="638" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/7ee2e757-0f4a-44b8-862a-6c20fc6558de">

**Comment by amanda-phet** [comment]
I think making all radio buttons vertical would be an improvement.

**Comment by samreid** [comment]
@catherinecarter is this one ready to implement? Are we going with the combo box?

**Comment by catherinecarter** [comment]
Yes. Let's go with the one where all the radio buttons are vertically stacked, the 2nd from the bottom. Thanks, @samreid.

**Comment by catherinecarter** [comment]
We are adding the Max Kicks to include 5 and 10 after today's PhET-iO meeting. Max kicks for the median screen will continue to have 15 as the highest. Default values will remain at 15. With the addition of the 5 and 10 max kicks, the Max Kicks choices seem better in a combo box (now that there are six choices). Notice the descriptions under each heading have changed.

![image](https://github.com/phetsims/center-and-variability/assets/109630002/c772d665-2c4f-44d7-81d4-3fd163d04224)

**Comment by marlitas** [comment]
@matthew-blackman and I chatted, and I went ahead and implemented the preferences pattern that had been discussed and then somewhat abandoned a few months ago. 

In terms of code, I think it's cleaner and more consistent... however in order for it to match @catherinecarter's mockup some changes need to be made to preferences in general. Some of that initial design discussion from a few months ago is tracked here: https://github.com/phetsims/joist/issues/842

I will start by saying I believe all these changes will make preferences stronger overall. 

**1. Control on same line as label AND description:**
Currently the control is on the same line as the label only.
<img width="584" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/79e1afa9-958e-4ef3-88ed-adddee239483">

That looks fine with a toggleSwitch but as you can see with the larger controls they now extend above the label. My recommendation here is to have the control in it's own column so that the controlLabel and controlDescription always live to the left of the control. This change would affect all preferences across the codebase.

**2. Wrapping description text earlier**
We are currently wrapping RichText at 480, the number that would match @catherinecarter's mockup is 300. This could be a CaV only change, but is probably worth pulling into the preferences conversation as a whole as well.

**3. Compensating for comboBox spacing ahead of time or dynamically?**

This one could be tricky and is the only change here that I would perhaps recommend punting until we are really digging into preferences work. Currently, the comboBox may cover another control if there are enough options in the comboBox
<img width="232" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/c8b18abd-74b9-4cdf-b0cf-de45384522c1">

By cleaning up everything else the result won't be as bad as what is pictured, and adjusting the height of a preferencesControl based on the needs of an expanded comboBox could have unseen repurccussions in preferences in other sims.

**Comment by catherinecarter** [comment]
@arouinfar is reminding us that the localization tab makes the preferences dialog box wide by default, so this may not be an issue, and since the CaV does not currently have this tab yet (it will), the box is not as wide as it will be in the future. This change to put the controls into their own column seems like it might be an easy or quick solution, but since we don't know the ramifications of this change on other things, and we're planning to update the preferences at some point anyway, we will table this.

In terms of the combo box, we could have the box open up rather than down, if we don't want to worry about the combo box dropping into other controls. Adding the ?locales=* query parameter solves the issue of the combo box dropping down below the bottom edge of the preferences menu box.

For the 2nd sentence for MaxKicks, we will make this all one line rather than a separate sentence as it looks disassociated from the title, "Max Kicks." 

For visual design, let's make the font sizes for the radio button group larger, and the size of the combo box smaller.

For wrapping text, we will keep it at the default so the wrap is consistent with other sims.

All these decisions were made with @kathy-phet, @matthew-blackman, @marlitas, @arouinfar, and myself, @catherinecarter.

**Comment by marlitas** [comment]
The above decisions and commits complete the large development portion of this issue, so I think it's ready for code review. Over to you @matthew-blackman!

**Comment by catherinecarter** [comment]
How about these icons? 
![image](https://github.com/phetsims/center-and-variability/assets/109630002/7654c471-7952-420c-84e4-75f7c48dbbbf)

**Comment by catherinecarter** [comment]
Oh, and actually, we could get rid of the text under Plot Type, too: 

![image](https://github.com/phetsims/center-and-variability/assets/109630002/7bb0d734-7b02-4dc5-97d6-1bc318057415)

**Comment by amanda-phet** [comment]
I like the icons for plot type! Seems really clear to me.

**Comment by marlitas** [comment]
Yeah that looks great. I'll go ahead and implement that.

**Comment by marlitas** [comment]
Okay that has been applied in the above commit! Let me know what you think

<img width="657" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/dbcf6577-a02e-457e-918a-229aa6f173a9">

**Comment by marlitas** [comment]
Reviewed design with @catherinecarter and all good to go there!

**Comment by matthew-blackman** [comment]
Looks great @marlitas. Using PreferencesPanelContentNode looks like a good paradigm to implement across the board. Checked in studio and confirmed that none of the preferences controls are instrumented. Closing.

**Comment by catherinecarter** [comment]
I saw @matthew-blackman's comment about the preferences controls not being instrumented and saw this in the tree: 
<img width="270" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/6fcaa322-db9d-47dc-851f-b0d3803ffa7c">

Reopened this issue since I want to verify this is not contradictory to @matthew-blackman's comment?

**Comment by catherinecarter** [comment]
Discussed with @matthew-blackman and all is well. Closing.
