### ISSUE TITLE
Rectangles in accordion box matching

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#280]
I noticed the rectangles in the accordion box are different heights for the different measures. Let's make them all match, especially after issue #279 is complete, we may want to revisit the heights of these rectangles as the size of the accordion box will be increasing.

<img width="263" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/8a92f063-8af3-459a-8a2f-5663191e95f1">
<img width="268" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/699b7a87-c0a3-4c0f-ac55-a1cf6f873a81">
<img width="266" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/df84cceb-9ce3-4b72-a33d-7eb32b04de50">

**Comment by matthew-blackman** [comment]
Do you mind mocking up how this would look for the IQR? Right now the brackets at the top are positioned so that they don't overlap with the title of the accordion box or other elements in the info box, so moving the box and whisker plot up would create issues with this. Looking through the code it seems like this would be non-trivial since the height of the rectangle is dynamic, and has different logic for the three measures. The MAD node can get particularly tall, so we'd need more specifics on how this should look for cases with tall stacks of data.

**Comment by catherinecarter** [comment]
That's a good point about the median arrow getting in the way of the rectangle height. What do you think of this?
![image](https://github.com/phetsims/center-and-variability/assets/109630002/3aad5091-becf-4810-8c0e-9c8b21f5e303)

In terms of the info box, I think the rectangles there being different sizes are ok. In the accordion box, though, since a user can toggle between all of them quickly, the disparity in height is much more jarring.

**Comment by matthew-blackman** [comment]
Looking really nice! Ready for your review @catherinecarter :)

**Comment by catherinecarter** [comment]
Looks really good! I am keeping this issue open because when the accordion box is extended in height, we may have to revisit this issue again to see how tall we want the rectangles while staying under the title.

**Comment by matthew-blackman** [comment]
This has been fixed as part of [1473f9c](https://github.com/phetsims/center-and-variability/commit/1473f9c3aff9710086be868724e484aec43e5a65) and design review complete by @catherinecarter. Closing.

**Comment by matthew-blackman** [comment]
Reopening to address remaining TODO

**Comment by matthew-blackman** [comment]
All TODOs have been addressed and the variability rectangles are sizing correctly. Closing.
