### ISSUE TITLE
Card alternate text property

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#285]
From https://github.com/phetsims/center-and-variability/issues/204

The user story is:

> Card visible property - per card

@marlitas and I observed that each card currently has a visibleProperty that can be toggled off.  This leaves a hole in the card container like so:

![image](https://github.com/phetsims/center-and-variability/assets/679486/2bfea9ac-e4ba-4e6d-8637-c9554929b07e)

Therefore, we would like to know more about this user story.  Is it so that clients can ask students to predict the value of a card? If so, would it be better to have a card with a '?' question mark on it?

**Comment by catherinecarter** [comment]
I would think the user story would, indeed, be to hide the card with the intent of predicting what value would be in it's place. I agree having something there would be useful, especially if the card hidden is the far most right card (you wouldn't know one is missing). Here's what it would look like with one card with a ?:
![image](https://github.com/phetsims/center-and-variability/assets/109630002/eb989729-c26d-4c77-9889-35d9281c5c14)

And if multiple cards were 'hidden:'
![image](https://github.com/phetsims/center-and-variability/assets/109630002/7cae3432-b035-4ed4-a0be-309d16a7313a)

**Comment by samreid** [comment]
Before starting, we should check if the alternate text needs to be internationalized.  I recommend against it, because that would make the cost exceed the value.

**Comment by catherinecarter** [comment]
@kathy-phet is questioning the pedagogical advantage to hiding the card's values and replacing with something else. Some example user stories/pedagogical moves could include:
- Making an explicit 1:1 correspondence connection between the ball positions and the values on the cards
- A question could be posed to ask students to work backwards, show the median, and then fill in the cards with possible values
   - This could be done if the balls are all hidden so there wouldn't be the visual cue

The underlying question is to create a move using the sim, and this feature doesn't seem to support these pedagogical user stories because they don't leverage the sim. 

Recommendation: Do not implement this feature.

**Comment by samreid** [comment]
In the commits, we uninstrumented card visibility, and instrumented the cardNodeContainer.enabledProperty. But we still need to hide the hand when cardNodeContainer.enabledProperty is false.

**Comment by samreid** [comment]
We reviewed that behavior, and agreed it is good, closing.  Does not need code review since it was trivial.
