### ISSUE TITLE
Instrument IntervalTool handles and pickability

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#286]
From the CaV PhET-iO Design Doc:

> Remove grab handles, and make it not pickable (user story: make a data set with most of the values in the yellow region) 

> CC: do this per handle rather than both together
> KP: Use both visible and enabled properties

According to this we need to:
- Instrument visibleProperty for each handle
- Instrument enabledProperty for each handle
- If either handle is not visible or enabled we will not allow horizontal translation either

**Comment by samreid** [comment]
What is the use case for disabling or hiding one handle but not the other? Is that a practical and important PhET-iO client wrapper scenario?  I'm asking because it may be much simpler in the code to handle all 3 (left handle + right handle + translatability) as a unit.

**Comment by catherinecarter** [comment]
An example of a use case could be for the instructional designer to manipulate a data set to have a certain mean. Then, pinning one edge of the interval tool on the mean could allow the other handle to explore variability from the mean to the MAD, for example. Another case could be a similar story but for the median while exploring quartiles. 

There's another possibility for where a ball is disabled and one edge of the interval tool is at the disabled ball. Exploring possible ranges from that ball could be an option.

Oh, one more I just thought of another question that could be posed: the mean of a data set is [insert fixed number]. With 10 balls on the field, what's the minimum and maximum median for this data set. The edge could be pinned to the chosen mean, and the other tool exploring the median. 

Do these possibilities makes enough sense to have one handle be able to be disabled?

**Comment by samreid** [comment]
Yes, sounds good to me, thanks!

**Comment by samreid** [comment]
I'll take a look

**Comment by samreid** [comment]
In the commit, we added support for enabled/disabled on all prediction slider handles. For the interval tool, it looks like this:

![image](https://github.com/phetsims/center-and-variability/assets/679486/3b15e1de-9bc6-44bd-8772-c3ea5f93bc3d)

For predict mean/median, it looks like this:

![image](https://github.com/phetsims/center-and-variability/assets/679486/961d7d56-3fa4-4457-ab04-33144befdc3f)

Adding this for predict mean/median was not requested, but it happened "for free" when we implemented it for the interval tool. If this is undesirable, we can add more code to remove it.

For the visibility, it is more complicated.  The visibility is already controlled by a linked element about whether the interval tool checkbox is checked:

![image](https://github.com/phetsims/center-and-variability/assets/679486/1cadd59b-e9b2-480f-af8d-0e0df8b684f0)

So I wanted to pause and ask if the `enabledProperty` is good enough. It would be more complicated if we have to add multiple "gates" to control the overall visibility of the handle.  We have done that in some cases, but prefer not to if we don't have to.

Also, in initial experimentation, it did not feel buggy that you could translate the entire interval tool with one or both of the handles grayed out. So I'm not sure that addition is necessary or valuable.  Also, I'm wondering if the way we want to control that would be by instead adding an `enabledProperty` on the `centerAndVariability.variabilityScreen.view.intervalToolNode` itself.  So this issue is at a good point for check in determination of next steps.

**Comment by samreid** [comment]
> Adding this for predict mean/median was not requested, but it happened "for free" when we implemented it for the interval tool. If this is undesirable, we can add more code to remove it.

@catherinecarter said it is good that a client can disable e.g. the predict median arrow

> So I wanted to pause and ask if the enabledProperty is good enough. 

@catherinecarter reviewed this and agreed that the enabledProperty is probably good enough for now.  If some client requests to make it invisible in the future, we can add that in the future.

> Also, in initial experimentation, it did not feel buggy that you could translate the entire interval tool with one or both of the handles grayed out. So I'm not sure that addition is necessary or valuable.

@catherinecarter said it is actually a nice feature to disable the handles and still be able to translate the body. Because then a PhET-iO client could fix the width but allow the student to position the translation. But we are thinking the a grayed out handle should mean "this handle is frozen in place".  But maybe another way to support the ability to translate a fixed-width interval. But we are thinking of these options:
* The interval tool width is fixed, but can be translated
* The interval tool width is fixed, but cannot be translated
Do we need to support both of these? How would we indicate these different modalities to a user?  Will this overcomplicate the PhET-iO implementation? 

We aren't sure about this part and would like to consult with @kathy-phet.

**Comment by catherinecarter** [comment]
@kathy-phet says that having the handles not visible could indicate the translate tool would not be allowed. With the handles showing, the translation of the tool would be allowed.

These feel like different things. Another possible approach: 
* Make an "is" property to represent the translation, and could be another thing you listen to
  * isTranslatable
  * isResizable
  * both boolean
* default would be 'isTranslatable' could be used
* probably the most used case would be fixing one of the edges and the other edge would be moveable

@marlitas pointed out this might make it challenging to fix one handle and move the other
@matthew-blackman says isResizable and isTranslatable would not be independent of each other

@marlitas has an idea for how to label the pieces, we could enable the translation as a separate thing, and make the handles visible or not rather than the enable properties entirely

Currently the isVisible property of the Interval Tool Handle is linked to the checkbox, which hides the entire interval tool rather than making one handle invisible. This is an unexpected interaction/feedback. 

@samreid says we could/should make the Interval Tool handle a child of the Interval tool itself (the rectangle), but says it might look strange in the tree.

Sub Decision: 
* Make the interval tool handle 1 and handle 2 to be children within the tree of the Interval Tool Node. These are actually not children, rather siblings, but we will pretend these are children to make the tree more parsable and easier to understand for the designer.

Decision:
* Get rid of enabled property on both handles, and instead use the visible property to indicate whether the handle can be moveable or not
* The translation ability is indicated by the hand cursor changing or not changing, this allows the flexibility of changing the position but not the width of the tool as well as fixing both width and position.

**Comment by samreid** [comment]
In the commit above, we set up the behavior like we like, but there is some commented out code and duplication of variables and tandem names that should be cleaned up.

**Comment by samreid** [comment]
We implemented this to work like we want it, last thing is code review for the last 3 commits, and get rid of the commented out code and duplicated tandem names and variables.

**Comment by marlitas** [comment]
I removed commented out code, consolidated tandems, and reviewed. It's looking good and no other changes from my end. Closing.
