### ISSUE TITLE
Allowing clients to set MaxKicks per player

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#287]
In the CaV PhET-iO Design Document we saw:

> Let instructional designer set total number of balls each player kicks. 

We are concerned about this implementation because it will be a large restructure of the CaV code. We want to confirm what the desired behavior is and if the effort spent is worth the feature in the long term.

What if the client sets MaxKicks = 25 how does this value coordinate with the individual kicks of each player?

Would this also affect the Mean and Median screen?

**Comment by matthew-blackman** [comment]
The devs discussed this with @catherinecarter and the following concerns were brought up:

- There are major structural changes that would be needed as maxKicks is a variable controlling both screens 2 and 3
- The preferences dialog has maxKicks set in increments of 5. If the instructional designer changes this per player, this will contradict the setting in the dialog box
  - This is possible but will be very expensive
- The behavior outlined in the PhET-iO design doc could be simulated by hiding the kick buttons after a certain number of balls are kicked.

The devs and designers agree that because this would be expensive to implement, but could create issues down the line if we absolutely need to do this, we'd like to discuss with @kathy-phet before making a final decision.

Labeling to discuss at CaV PhET-iO meeting.

**Comment by samreid** [comment]
In today's phet-io meeting, we agreed to allow the values 5 and 10 in the maxKicks. Screen 1 could have a max of 15, but could go down to 5 or 10.  Here's a patch that does most everything except for the median screen. @catherinecarter will update the design in #275
