### ISSUE TITLE
Allow client to create and display a preset measure of spread

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#291]
From the CaV PhET-iO Design Doc:

> Create/set a measure of spread (range, boxplot, MAD and before any soccer balls kicked yet) so students could create a distribution matching the spread.

> Client would put that in the wrapper and have students mimic the distribution they’ve created.

This seems like complex functionality that would need to decouple the spread measures from the balls in the play area. Probably best to discuss as a team on what the best approach here would be.

**Comment by matthew-blackman** [comment]
In discussing this with @catherinecarter, we agree that the interval tool can be used for the purpose described in this issue. Rather than updating the sim, we recommend that clients do the following:

1. Place the interval tool on the stage and set it to a width/location that they want the student to match.
2. Disable the handles and enabledProperty of the interval tool so that it cannot be moved.
3. Have the student to position soccer balls to match the corresponding measure of spread.
4. Use the plots in the accordion box for students to check their work.

We feel that the interval tool provides enough flexibility that we don't need to add any features to the variability plots or accordion boxes. Closing.
