### ISSUE TITLE
Sound sign off + balancing

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#304]
This issue is to ensure the team signs off on the sounds, mapping, and interactions expected in the sim. 
Once we're done with sound and you've gone through the sim to verify the 
- sounds are what you expecting them to sound like, 
- happened when you expected them to happen, 
- are consistent across screens, as expected, and 
- the volume levels are where you are expecting them to be, check your name off this list.

List:
- [x] Kathy
- [ ] Emily
- [x] Ashton
- [x] Sam
- [x] Marla
- [x] Matt
- [x] Cathy

**Comment by marlitas** [comment]
This is now ready for everyone to take a listen and provide feedback!

**Comment by marlitas** [comment]
I listened through and thought all the custom sounds were well balanced! However, the default sounds all were very loud and jarring to me. Especially the reset-all button, the info Dialog button, and the open-close on the AccordionBox. I also felt the radioButtonGroup in the third screen were too loud as well. 

I'm not sure how it works with all the default sounds, but perhaps that means the custom ones need to be turned up a bit to match if the default can't be brought down? I'll wait for @Ashton-Morris and @emily-phet to weigh in on that.

**Comment by Ashton-Morris** [comment]
@samreid Is there a way to listen to the sim with all the non UI (tambo) sounds turned up 10% (except the the eraser sound)?

I do see what @marlitas is saying a little. But our UI volume levels are consistent across all sims so it would mean altering all non UI sounds up in volume to address this.

**Comment by marlitas** [comment]
Committed above. I think this is a better starting ground for balancing. The tambo sounds aren't as jarring to me anymore. With these changes I would turn down the soccerBalls just a bit. I know we want them to be louder than most everything else but this is probably a bit too much at the moment. 

Thoughts? 

Also, if we don't like it should be easy to revert.

Also, also... I don't know if I interpreted the increase 10% correctly. I changed the outputLevel percentage by 0.1 instead of calculating what a 10% increase of the current level was... If I was supposed to do the latter let me know and I'll correct it.

**Comment by samreid** [comment]
Testing the current version, it seems pretty well balanced to me. My only thought is to reduce the card movement volume by about 15%.

**Comment by marlitas** [comment]
Pinging those who are still assigned and need to sign off/ provide feedback:
@kathy-phet 
@emily-phet 
@Ashton-Morris 
@catherinecarter 
@matthew-blackman

**Comment by Ashton-Morris** [comment]
Sounds good in my opinion!

**Comment by catherinecarter** [comment]
Sounds are well-balanced to me, and the changes to volume levels sound great. I'm signing off! Yay!

**Comment by kathy-phet** [comment]
Overall, I really love the sound in this sim. The pedagogical assistance of the tone scale is great, and its so easy to hear that the median and mean are not the same when you toggle them on, and know which one is less. Wonderful! 

There was one sound that I wasn't crazy about. I don't think I had played with it directly myself previously - and maybe only heard it over zoom or it was one of the meetings I missed for one reason or another. It's the eraser sound. It is a common code component, so I'm wondering if the eraser sound is new to this simulations? Or was it previously designed? It think something similar would feel better to me if meaning to go literal with eraser. It feels a like it doesn't really fit with the "feel" of the other general UI sounds. Does anyone else have that sense? If its just me, then I can live with it. I mention it in particular, because it is a common code UI component, so will be used in multiple sims that have erasers that Amanda, Amy, and others are designers on as well.

**Comment by arouinfar** [comment]
> It's the eraser sound. It is a common code component, so I'm wondering if the eraser sound is new to this simulations? Or was it previously designed? It think something similar would feel better to me if meaning to go literal with eraser. It feels a like it doesn't really fit with the "feel" of the other general UI sounds. Does anyone else have that sense? 

I feel the same way @kathy-phet. I haven't heard this sound before, but it feels a bit off to me. The sound is really short, so we miss out on the repetition that cues erasing. I also share @kathy-phet's reservations about using literal sounds for standard UI components. 

If we want to go more general, I think a whoosh like [this](https://www.youtube.com/watch?v=HoRvO_H_v-s&ab_channel=Antoni1018) or [this](https://www.youtube.com/watch?v=KwnY7R2Q06M&ab_channel=MommySallyU) could work.

**Comment by catherinecarter** [comment]
Seems like all sounds are balanced and signed off. Closing this issue and will open a new issue regarding the eraser sound.
