### ISSUE TITLE
Translation sound of the entire interval (continuous or pulsing)

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#309]
From https://github.com/phetsims/center-and-variability/issues/236, we need to decide if we want the sound to be continuous, or to pulse (when passing points on the number line) when the entire intervalTool is translated side to side.

**Comment by samreid** [comment]
Based on discussion with @marlitas @catherinecarter @matthew-blackman and myself, it sounds like we should try the pulsing sound.  We think it could be more enjoyable and also match well with other sounds like dragging the mean prediction arrow.

**Comment by samreid** [comment]
Should we get more design feedback on this before implementing it?

**Comment by matthew-blackman** [comment]
This is related to recent changes from https://github.com/phetsims/center-and-variability/issues/308. Not sure how the pulsing sound would affect this, but wanted to bring it up in case the sound behavior changes.

**Comment by Ashton-Morris** [comment]
I am interested to hear the pulsing sound.

**Comment by emily-phet** [comment]
I think @samreid had an example in mind. It will be hard to have an opinion how to proceed without an example. Perhaps @samreid could revive that example, or work with @Ashton-Morris so that an example can be mocked up. 

I trust @samreid's opinion that what he heard of this sounded good, and worth exploring for this tool and other scenarios where a continuous tone is being considered. This particular context has some specific differences from Gravity Force Lab/Basics that might allow for more flexibility. In GFL/GFLB we could not have pulsing, as the mapping is to a continuous change in force and that changing force value is a primary focus in the sim. With this interval tool, the pulsing may work as the interval tool is associated with a number line that is continuous, but does have discrete labeled values and is sometimes utilized in a discrete manner so it might not seem discrepant. The interval is also not most important thing in the screen, which also provides a little more leeway to be experimental.

**Comment by catherinecarter** [comment]
Now that the tolerance has been decreased, the pulse is very distracting. It almost makes it sound like a warble when the car windows aren't balanced. We will need to explore a lower tolerance for when the pulse happens, or remove the pulse and go back to considering the continuous sound. 

I would love to hear examples of no pulse, or pulse less often. Not sure how the tolerance for how big the wiggle is when moving the handle(s) or translating will work. We will work on this and bring some examples to the next sound meeting.

**Comment by matthew-blackman** [comment]
@samreid suggested the option of having the interval tool use a similar sound behavior as the mean tool, where it plays a sound whenever the width of the tool had passed a certain increment. We can definitely experiment with the options you suggested above but I wanted to put this on your radar as well. How does that sound to you @catherinecarter?

**Comment by samreid** [comment]
@matthew-blackman and @marlitas and I also discussed that we might want to indicate stripes or tickmarks on the interval tool rectangle itself, so it is clear when you pass by an integer or half-integer width.

**Comment by catherinecarter** [comment]
@matthew-blackman and @samreid, I'm open to seeing/hearing options for sure. We'll want to keep in mind that this tool is an open-ended tool for the user to interact with and use for the purpose they see fit. The most important thing is the width of the tool rather than its position on the number line, and the pedagogical importance of the screen are the soccer ball positions and the abstract representation in the accordion box. It sounds like we may be putting too much focus on the tool, but I'm interested to see/hear whatever work has been put into it in action.

**Comment by samreid** [comment]
We got the continuous sound working much better in #310, so we would like to discontinue the pulsing idea, closing.
