### ISSUE TITLE
Should we create CardContainerModel?

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#314]
From https://github.com/phetsims/center-and-variability/issues/284 and related to https://github.com/phetsims/center-and-variability/issues/283

> While investigating this, @marlitas and I observed that there is no model for the order of the cards--it is all handled in the CardContainerNode. So we should investigate better model/view separation for that.

**Comment by marlitas** [comment]
@samreid, @matthew-blackman, and I chatted about this, and decided that we want to do this correctly. There are a lot of muddled aspects right now, but believe that starting in baby steps is the way to go with this. A good place to start may be with separating out the positionProperty and animation in CardNode out to the model.

This is not a high priority for @samreid before his vacation time.

**Comment by marlitas** [comment]
> I did run into an error when setting a card's cellPositionProperty. It looks like setting it didn't impact the card's position, and then trying to drag a card caused the following:
Mmm good catch. I think the cellPositionProperty should be readonly. I'll update that.

1. I think it needs to be instrumented for state, but perhaps we can make it readonly? I'll double check the state thing though.
2. I also tend to agree that we probably don't need to instrument setting the position of the dragIndicator, but it will probably be good to double check with @catherinecarter before moving forward on that. making it readonly might be enough to solve this, but if we do want to move it around we'll have to look a bit deeper into what's going on.
3. That's definitely a design question... Let's check in with @catherinecarter.

**Comment by catherinecarter** [comment]
Can you help me understand what the question is? I see a comment about the cellPositionProperty, but then another comment about the dragIndicator. 

I agree the cellPositionProperty should be readOnly. Can you help me understand how these two are connected? Thanks!

**Comment by marlitas** [comment]
> Can you help me understand how these two are connected? Thanks!

They are just connected because of a code refactor.


The two big questions for you are:

1. In studio, dragIndicationCardProperty behaves in a way I didn't expect. If I click 'Get Value', its phet-io ID is "centerAndVariability.medianScreen.model.cardContainerModel.cards.card1". But if I try to change the last part to "card3" and click 'Set Value', nothing happens. I also tried pasting the 'Get Command' code in the console and nothing happened. But I'm wondering, does this need to be instrumented at all? Having the drag indicator over the leftmost card seems to make sense to me, and I think its visibility would be enough to instrument via PhET-iO. Thoughts @marlitas?

2. Should the cards value be more accessible via studio, even if they are read only? Right now to see a card's value, the user needs to navigate to the linked soccer ball.

**Comment by marlitas** [comment]
`cellPositionProperty` is now readOnly.

**Comment by catherinecarter** [comment]
I see. Thanks!

I also noticed the Set Value didn't do anything. I was trying to figure out why nothing happened. 

1. To add commentary (not sure it's a decision), I can see an instructional designer wanting to put the dragIndicator on a specific card, perhaps to encourage students to notice a particular card, like maybe it's only one out of order. I can also see the indicator being on the left-most card always since it's purpose is to help the user know you can move the cards. 

2. I believe you can currently get the value of all the cards as an array via the console, which gives all the values of the cards in the order they currently are (#283). I'll keep thinking about whether the cards should be more accessible via studio. 

I don't think I provided any clarity. I'll keep thinking on it and contribute again soon.

**Comment by marlitas** [comment]
> Does totalDragDistanceProperty need to be instrumented? We could instead use a boolean for 'showDragIndicator' if we want to be able to customize the drag indicator - any reason to expose the actual drag distance via PhET-iO?

Turns out totalDragDistanceProperty is not needed for state. I removed it's instrumentation and all seems to be working well.  @matthew-blackman, want to double check it?

**Comment by marlitas** [comment]
During a check-in we decided:
1. `dragIndicationCardProperty` should be readOnly. Clients do not need to be able to set it's position. 
2. We do not feel like it is needed to add another valueProperty to the card. We could not think of a strong enough client usage case to add this in.

**Comment by marlitas** [comment]
The above commit addresses all the review comments that are left. I believe this is now ready to close, but please feel free to re-open if there is something else. Thanks @matthew-blackman!
