### ISSUE TITLE
Interval tool should stretch to just under the top of the accordion box (just under the margin)

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#319]
Currently looks like this:

![image](https://github.com/phetsims/center-and-variability/assets/679486/98326bbf-f9d0-4346-a99f-3d35e54f0041)

**Comment by matthew-blackman** [comment]
Ready for review @catherinecarter :)

**Comment by catherinecarter** [comment]
Looks great, as it's taller now to match the change in height in the accordion box. I'd like to bring it down a bit (sorry!) to be just under the title rather than going behind it. So the top of the rectangle will be between the bottom of the title and the top of the numerical spread measure.

Thanks!

**Comment by matthew-blackman** [comment]
No worries @catherinecarter! Let me know if the latest changes are what you had in mind 🙂

**Comment by catherinecarter** [comment]
Looks really good. Thanks! I'm good from my end to close.
