### ISSUE TITLE
Sound effect + Animation when checking "sort data" when the data is already sorted.

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#333]
From https://github.com/phetsims/center-and-variability/issues/245#issuecomment-1609959744

> Single sound for when cards are already sorted, perhaps a slight animation. Then if you click "sort data". It would play a single flutter sound, instead of that sound that sounds like an error. Just one flutter. And use the celebration animation where the cards get a bit bigger then a bit smaller.

**Comment by samreid** [comment]
I implemented a rough draft in the commit.  

* Make the cards bigger then smaller like celebration1
* When the animation starts, play a "card pick up" sound
* When the animation ends, play a "card drop" sound
* Note: just using the existing celebration1 out of the box was very buggy because of the following reasons:
  * Clicking the checkbox rapidly caused the cards to grow since it didn't have time to go back to the initial size before starting to grow again
  * If you click the checkbox rapidly as cards landed, the re-centering of the cards throw off the layout and left gaps and bugs. 
* Therefore for this rough draft, the scaling is not centered, it is down and to the right.  This is not my preferred design but I could not get it to work without bugs otherwise.  Would be good to collaborate with @marlitas and @matthew-blackman on that part.

Aside from that, the rest is ready for review and discussion. @catherinecarter can you please take a look?

**Comment by samreid** [comment]
We reviewed this at today's sound design meeting and agreed it sounds good.  Over to @marlitas and @matthew-blackman for code review.

**Comment by marlitas** [comment]
@samreid I'm a little confused about the `adjustCentering` argument in `this.animateCelebration1`. Perhaps this is what you were referencing in https://github.com/phetsims/center-and-variability/issues/333#issuecomment-1610406697? 

I'm also wondering if this scale property should live in the cardModel, but I'm unsure there. This might be good to tackle with @matthew-blackman since @samreid is on vacation right now.

**Comment by matthew-blackman** [comment]
@marlitas and I reviewed this and felt that it's looking good. We changed the name of the `adjustCentering` parameter to `animateFromCenter` for clarity. We also reviewed the properties that are created and linked in the animations, and felt that it makes sense for this to all be in the view since it is strictly dealing with card animation.

We also noted that it doesn't look like the properties created in the animation celebrations are being disposed. We wonder if this could create a memory leak and want to check in on this during performance testing.
