### ISSUE TITLE
Card PositionProperty should be readonly

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#354]
With @catherinecarter we saw that a CardNode's position property was instrumented and clients could change it's x and y coordinates. This seems weird so we would like to change that property to readonly.

**Comment by matthew-blackman** [comment]
Implemented and reviewed with @marlitas. We noticed that the cardPosition updates when you try to drag a card (even if its screen position does not change). After discussing we feel that this is okay, since the card container also has a getData API to get the actual order of the cards. Closing this issue, we can revisit if this comes up in QA.
