### ISSUE TITLE
Fix DragIndicator Value logic

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#356]
In studio @catherinecarter saw some strange behavior from the dragIndicator whenever the isDragIndicatorVisibleProperty toggles. It seems like sometimes the dragIndicator value is randomly set to a number that isn't included in the values of the balls.

**Comment by matthew-blackman** [comment]
Fixed and would be good to review @marlitas. The issue was that the drag indicator value was only being updated if it was visible. This created issues when the soccer ball it was attached to changed stack while it was hidden. I removed the visibility guard and everything looks good.

**Comment by marlitas** [comment]
The code looks good and I did a quick test of the behavior in studio. @catherinecarter can you confirm the behavior for the DragIndicatorVisibleProperty is working as you'd expect?

**Comment by matthew-blackman** [comment]
Reviewed with @catherinecarter and the behavior is mostly good but we are still running into a problem with setting the dragIndicatorValueProperty via studio. The current beahvior is that the dragIndicatorValueProperty will update when its associated soccer ball is moved, even if its value was manually set via studio. We'd like to discuss this with @arouinfar.

We think a simplified behavior would work well here, where the user can set the position of the drag indicator via studio and it stays in that position. We didn't mind if the drag indicator appears in a spot where there is no ball in studio, because the user could just update its position via the dragIndicatorValueProperty.
