### ISSUE TITLE
the median value shouldn't show a decimal if it is an integer

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#364]
From #325  @matthew-blackman and I thought the median value shouldn't show a decimal if it is an integer:

![image](https://github.com/phetsims/center-and-variability/assets/679486/a6574de6-fc26-4ce2-a09e-433552c9cfb1)

**Comment by samreid** [comment]
Proposed fix in the commit:

![image](https://github.com/phetsims/center-and-variability/assets/679486/6e4ff37d-d01e-4a86-9687-004064b6af7a)

@marlitas can you please review?

**Comment by marlitas** [comment]
Should `return value === null ? valueUnknownString : typeof decimalPlaces === 'number' ? Utils.toFixed( value, 1 ) : value;` use `decimalPlaces` in the Utils.toFixed instead of the number `1`? Or are we assuming that we will always round to `1` decimal place?

If the latter I think `decimalPlaces` should be a boolean that tracks wether we're an integer or not... perhaps `isInteger`, or `roundToTenth`.

**Comment by marlitas** [comment]
Looks great! Closing.
