### ISSUE TITLE
Provide way to close infoDialog through keyboard input

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#372]
When working on https://github.com/phetsims/center-and-variability/issues/257, I discovered that there is currently no way to exit out of the infoDialog with keyboard input. I assume there is a step we missed in the info dialog that we just need to add in. Will look to other sims with dialogs to see their implementation.

**Comment by jessegreenberg** [comment]
Hey, I just saw this issue go by.  I believe this is happening because the InfoDialog is in the screenViewRootNode PDOM order:

https://github.com/phetsims/center-and-variability/blob/5a1d6b6458ab90ffdcf23cb2a00707b48e4a33ed/js/median/view/MedianScreenView.ts#L80-L90

When the a Popupable is shown, ScreenView content is removed from the traversal order. By putting the Dialog in the ScreenView's pdomOrder, its accessible content will be hidden when the Popupable is shown.

Would it work for your sim to remove the infoDialog from the screenViewRootNode pdomOrder?

**Comment by marlitas** [comment]
Thanks @jessegreenberg! That's exactly what it was. This can be closed.
