### ISSUE TITLE
How should it look if the mean and median prediction indicators are at the same location?

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#39]
If the user wants to predict the mean and the median are the same value, how should it look?  Should we make one handle larger?  Right now one completely obscures the other.

**Comment by amanda-phet** [comment]
What do you think about allowing them to be at the same location? We did that in NLD. See the generic screen, and how you can overlap two points/handles: https://phet.colorado.edu/sims/html/number-line-distance/latest/number-line-distance_en.html.

**Comment by samreid** [comment]
@chrisklus and I reviewed number line distance, and it does not seem like an optimal user experience that one can completely obscure the other.  What do you think about having one handle longer than the other (by one sphere diameter), so you can always see and drag both?

**Comment by samreid** [comment]
We discovered this problem is somewhat less severe now that the mean predictor is continuous.  So they can be nearby without being on exactly the same spot.

**Comment by amanda-phet** [comment]
Ideas that have been discussed are: 
* Make the handles different lengths
* Make the handle weights different so that when they overlap, the thicker one is always visible behind the thinner one
* Making sure that the "active" handle is always on "top" of the other one. It is weird that the mean handle is always in the back, and difficult to grab if you just dropped it behind the median one 

I don't think we came to a consensus yet as a design team about what to do for this issue because I can't find any meeting notes about it. I'm fine waiting on this and lowering the priority.

**Comment by samreid** [comment]
@amanda-phet do you want to do anything on this for today?

**Comment by chrisklus** [comment]
From dicussion with @amanda-phet and @samreid today - for today, we would like to move the grabbed indicator to the front, and start the mean indicator at 1.5.

We also noted that we still aren't sure what to do about the "same spot" problem and will not do anything differently for the milestone.

**Comment by chrisklus** [comment]
@samreid and I made the requested changes above and will remove this issue from the milestone in case we want to revisit it for 1.0

**Comment by samreid** [comment]
@catherinecarter can you please review this issue and advise?

**Comment by catherinecarter** [comment]
I think it's fine as is. Closing.
