### ISSUE TITLE
Sounds should play when moving a ball with keyboard input

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#420]
Currently no sound is heard when interacting with soccerBalls with keyboard input.

**Comment by samreid** [comment]
Implemented in the commit and could use design and implementation review. At the moment:
* If the user selected the "median" checkbox, it plays the median sound, as it does for mouse dragging
* When reaching the end, it continually plays the same sound over and over rather than an out of range "bonk"

While working on this, it also seems like the musical scale is off by a whole note. I'll open another issue for that.

**Comment by marlitas** [comment]
Thanks for that fix @samreid. This looks like a good straightforward implementation. Good to go for code review. @catherinecarter feel free to close if all looks good.

**Comment by catherinecarter** [comment]
The keyboard tabbing, picking up, moving with arrows is working well and as expected. The sound did not play when pressing a number to jump the ball to a new location or using page up/down keys, and is in a new issue (#428). Closing this issue since #428 is open now.
