### ISSUE TITLE
Add Keyboard hints 

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#433]
From https://github.com/phetsims/center-and-variability/issues/412, @terracoda said:

Also, for keyboard interaction, for a two-step drag, you will need a visual hint on focus to "Press Space to Grab or Release", until the first successful grab action. And on first successful grab you might want left and right arrows or just a single right arrow if the hint appears on the first card.

Here's an example from Friction. There are similar examples in BASE and FL.
<img width="771" alt="Screen Shot 2023-08-02 at 10 37 15 AM" src="https://github.com/phetsims/center-and-variability/assets/1902116/5f54bfca-89df-468e-9210-bacb37eebbc3">
<img width="771" alt="Screen Shot 2023-08-02 at 10 39 01 AM" src="https://github.com/phetsims/center-and-variability/assets/1902116/5e339794-ff89-4b6a-9016-fc96691479f0">
<img width="770" alt="Screen Shot 2023-08-02 at 10 37 58 AM" src="https://github.com/phetsims/center-and-variability/assets/1902116/26a3332a-8916-49a6-ba7d-9e1c9b15442a">
<img width="770" alt="Screen Shot 2023-08-02 at 10 38 32 AM" src="https://github.com/phetsims/center-and-variability/assets/1902116/aeddecd6-a65d-44b6-92d5-ee1d876e6f97">

In the case of Friction, the book moves in all 4 directions, but in the case of the cards and balls, you are a limiting things to a two directions.

First step is confirming what we want to keyboard hint to be. Over to @catherinecarter to confirm language and design.

**Comment by catherinecarter** [comment]
Here are some screenshots for ideas of language and design. 
For the play area, 
- the "press space to grab or release" will center above the ball being chosen. I was mindful of when the user has the Median checkbox checked.
   ![image](https://github.com/phetsims/center-and-variability/assets/109630002/584008f7-0eac-4e5f-9255-e5da04cb7b3e) 
![image](https://github.com/phetsims/center-and-variability/assets/109630002/b0140ba7-2bf0-4689-9c58-e5352f341269)

   

- for the cue to move, I repurposed the former blue cueing arrow and made it the same color as the dotted outline when a ball is selected. I had to think about the case when the user had the median arrow above the selected ball, so the arrows can't go above the ball, or not intuitively at least: ![image](https://github.com/phetsims/center-and-variability/assets/109630002/5e883719-6bcb-4fb3-b48d-d49ab80fd37e) 
![image](https://github.com/phetsims/center-and-variability/assets/109630002/de5ccfa4-bb09-4aee-9e8f-0218b7093409)


On the cards, I was conflicted. If there's only a right arrow, will the user know they can move any card right or left? Or will the right arrow be sufficient? And on the flip side, if there are both left and right arrows, and the user tries to move the leftmost card left, nothing will happen. Will they think the card doesn't move at all? 

Additionally, if the user has the median checkbox checked, any cueing information above the cards will occlude the median. I'm also unsure whether the "Space to Grab or Release" should be centered under the highlighted area, or closest to the hand. Here are some options and scenarios, would love feedback.
![image](https://github.com/phetsims/center-and-variability/assets/109630002/949b2b45-35b7-4eef-9357-dd48ccae54ec) ![image](https://github.com/phetsims/center-and-variability/assets/109630002/2bd6ff27-3424-4ecd-a198-e50425135fce)  ![image](https://github.com/phetsims/center-and-variability/assets/109630002/cdd64d60-bca0-4e9e-ac37-7611d22707c9)  ![image](https://github.com/phetsims/center-and-variability/assets/109630002/fb0c3309-4e50-494a-bd30-61b52f901874)  ![image](https://github.com/phetsims/center-and-variability/assets/109630002/cb3d48c9-2882-4277-9c10-1930ce6d4ce3)  ![image](https://github.com/phetsims/center-and-variability/assets/109630002/a48ecfcc-c289-42f7-926e-d721e8c96569) ![image](https://github.com/phetsims/center-and-variability/assets/109630002/a80e48d8-cd28-4b52-81ce-7825c8434de9) 
![image](https://github.com/phetsims/center-and-variability/assets/109630002/31b7ba0e-51ee-43ea-9b6c-83bc00f509ea)
![image](https://github.com/phetsims/center-and-variability/assets/109630002/bc862600-756e-48f8-9680-b4734b6c5ff4)
![image](https://github.com/phetsims/center-and-variability/assets/109630002/b55e49e8-9738-4785-b654-afc452b5dc61)
![image](https://github.com/phetsims/center-and-variability/assets/109630002/1759defe-95cf-4c97-8ec9-384b27625447)

Thoughts?

**Comment by marlitas** [comment]
This sounds like a great design meeting contender. @catherinecarter would you be able to set something up where @terracoda could join so we can all discuss these options synchronously?

**Comment by terracoda** [comment]
On keyboard focus, the hand cue needs to disappear. 

Wondering if you need a hand? Maybe a more prominent arrow is enough for both pointer- and focus-based input?

**Comment by terracoda** [comment]
Interactive Highlights (when enabled) will also help cue that the cards can be moved/sorted.

**Comment by catherinecarter** [comment]
I sent a calendar invite for tomorrow at 11am MT. See you then!

**Comment by terracoda** [comment]
Here's what @terracoda remembers from the meeting:

- Change the hint to be a combined hint:
    - Combined hint to be [Arrow Keys] to Choose    [Space] to Grab or Release
    - Do not move the hint when a learner is moving group focus to choose a card or ball.

**Logic of appearance of the hint:**
1. Hint appears within the group (cards or kicked balls) on keyboard focus until there is a successful grab interaction.
2. A successful grab of a card, means next focus on the group of cards will not get a hint, but if a kicked ball has not yet been successfully grabbed, the hint would still appear on focus of the group of kicked balls.
3. Upon tabbing to either group, the pointer hint disappears, and the keyboard hint takes over cuing.
4. If there is mouse click on a card or ball that has the keyboard hint, focus is lost and the hint disappears. If there has not yet been a successful grab, on next focus of the group, the keyboard hint re-appears on focus.
5. Keyboard hints re-appear after a reset or page re-load.

**Where to place the hint:**
- The hint cues the same ball that the pointer hint cues (e.g., the last kicked ball when all balls have been kicked). It cues the first stack of balls if not all balls have been kicked and there is no pointer hint.

**Arrows:**
- @catherinecarter is working on arrows that could be consistent across both the cards and the balls, and possible pointer.
- Arrows show up after pressing Space or Enter to grab, and the bigger hint box disappears.

**Extra Details**
- Both Space and Enter can grab the items even though we only cue Space - that's just how buttons work. 
- Your tracking a successful grab. If someone grabs, but doesn't move, I think the hint can disappear. That's how it works in Friction. There is design flexibility here.
- With interactive highlights on, learners get the pink highlights and the visual pointer hints (not the keyboard hints).

Hopefully, that captures most of it.

**Comment by catherinecarter** [comment]
Yes, I think that captures the logic. Thanks @terracoda!

After thinking about the pseudo-dialog that pops up indicating space or enter will grab/release a ball, I'm wondering if, instead of adding the information about the arrows to move focus to a different stack/card, there could be a cueing arrow on the ball. So the dialog would still just say, "Space to Grab or Release," and the same cueing arrow would appear after the space bar (or enter) has been pressed. That way, the cueing dialog can stay smaller (better for the cards), and the cue is consistent for similar interactions. I'm concerned about the cueing arrows above the soccer balls. Is it clear they're for the focus?

**Play area**
- Prior to tab moving to ball group
  <img width="553" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/21ceab3b-a5f4-4e6d-a171-bd8760a95f09">


- Upon tabbing to the soccer ball group: (the arrows disappear once user moves focus to a new stack)
   - if the focus is on the left-most ball (I'm a little concerned the arrow isn't clear since it's pointing to the ball next to it)
        <img width="609" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/3998620b-5c3b-42b5-91ff-499aba4693f7">

   - if the focus is on a non-edge ball  
      <img width="611" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/6b4beaf5-90ef-4e12-8a39-f508ebc20273">


   - if the focus is on the right-most ball 
      <img width="612" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/9bb7dac4-6340-42c5-b920-1c4465f77f69">


- Upon Space or Enter being pressed (arrows reappear once the space/enter is pressed, disappear once a ball is moved, and whether there would be one or two arrows would carry the same logic as above)
   <img width="550" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/afd32c4a-5e6d-441d-b2b7-ed01e9dbf6c9">

**Cards**
- Prior to the tab moving to the card group
   <img width="746" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/d3225dc0-d2f9-4f16-a1cc-be69cc3d7033">

- Upon tabbing to the card group (original cueing hand disappears)
   <img width="751" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/29dff3a4-c12b-4f6f-b6f9-f35506e814f8">


- Upon the user moving to another card (prior to space/enter, the arrows disappear)
   <img width="949" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/ac6ceaac-bab9-4251-97dd-e01cece5198a">


- Upon Space or Enter being pressed (arrow disappears once a card has been moved)
   - if the first time space/enter is pressed on the left-most card  
       <img width="765" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/36f5b6b9-c724-4334-9ea8-3d5a48f19357">
   - if the first time space/enter is pressed in a non-edge card
      <img width="765" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/e96df712-7b48-48b9-af58-7b0a6716869b">
   - if the first time space/enter is pressed on the right-most card
       <img width="931" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/70504557-91be-4005-baac-6ef8155bd19b">

**Comment by catherinecarter** [comment]
Or new arrows: 
<img width="554" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/5b84fc20-a71b-429c-893c-6719db9c79e5">

<img width="814" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/2b783a92-8215-46ce-8286-f3037eb2b62f">

<img width="809" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/621bd425-ff0d-4b48-a84c-546810e02c10">

**Comment by marlitas** [comment]
I think we should stay consistent with the arrows being used for the dragIndicator already. This also helps that we won't have to worry about edge pieces on the soccerBalls.

**Comment by catherinecarter** [comment]
I agree. Having the arrow be consistent will allow for a more fluid experience by the user when tabbing. If the arrow is already there, when the soccer ball group is tabbed to, only the hand will disappear, leaving the arrow above the ball that already has focus. We'll have to make the arrow a little bigger and move it up slightly as to not occlude the focus rectangle, but I think it will be ok. The arrow will be double-sided always. 

Is the current asset enough to scale it in the sim, or should I upload a new one?

**Comment by catherinecarter** [comment]
Sounds good, thanks! I am curious if we could make the arrow on the card hand bigger, too? So it's not a huge leap from the hand with the arrow to the standalone arrow when focus gets to the card group?

**Comment by marlitas** [comment]
Notes for MS:
Added the keyboard hint for cards. 

Up next:
- create new property that tracks if a card has ever been grabbed (not just moved)
- Hide drag indicator when hint is visible
- center hint along bottom of cards

**Comment by marlitas** [comment]
hasGrabbedCard's value update was removed during a refactor in https://github.com/phetsims/center-and-variability/issues/441. Added back in above.

**Comment by marlitas** [comment]
Next steps for cards:
- [ ] Add move to different card in group arrow
- [ ] 2 arrows (theoretically), one disappears when card is dragged, one disappears when you move to a different card.
- [ ] Move keyboard hint down to give space for arrow.

SoccerBalls:
- [ ] Keyboard hint floating in middle of sky
- [ ] Move cueing arrow up for all contexts
- [ ] Make the cueing arrow bigger for all contexts

**Comment by marlitas** [comment]
Okay, the keyboard hints for cards is done. 

I think this is a good spot to get code review for the cardContainer portion of this issue only. There is a magic number that I was still not able to suss out (see: `//TODO: Check the plus 1 magic number`). However I don't think it's worth spending an insane amount of time on. If the reviewer would like to take a gander and see if they can figure out the magic number I'd be happy for the extra set of eyes, otherwise I'll just throw it out as an empirically determined pixel polish.

Some history of what I checked:
- offset delta
- cardNode lineWidth
- InteractiveCueArrowNode line widths

Over to @samreid or @matthew-blackman for review on the work done so far. I will continue on implementation for the soccer balls.

**Comment by samreid** [comment]
We had an intermediate check-in, things are going well, and @marlitas can continue. Thanks!

**Comment by marlitas** [comment]
Okay! I believe this is now ready for both design and code review. I tried testing various scenarios to make sure hints were appearing and disappearing when they should, but please test out on your own machines and report any funky behavior.

**Comment by catherinecarter** [comment]
The behavior of when the arrows appear disappear looks great! The size of the arrow also looks really good.  

In the soccer ball area, a couple things I noticed: 
- the arrow needs to be raised a bit since the arrow currently is sitting at the top of the focus rectangle
- when I kicked all the balls, the focus rectangle went to the leftmost stack rather than where the hand cue-to-move was
- I'm curious how often the "Space to grab or release" dialog would occlude a ball if we move the dialog closer to the soccer balls - seems a little high to me

For the cards:
- the cue to move (arrow) when first tabbing to the card group is getting completely lost under the focus rectangles. I'm unsure how to solve it and have a meeting with AP later today to discuss

**Comment by catherinecarter** [comment]
I met with AP and we have a solution I'd like to run by you. Will do during standup today 8/25.

**Comment by catherinecarter** [comment]
In discussions with @ariel-phet, @samreid, and @matthew-blackman, we have decided to do the following things to solve the issue of the arrow getting lost without adding significant time/cost to the project.

- Move the "Median = " readout currently above the cards up
- Move the entire row of cards up
- Extend the focus rectangle at the bottom to add more room for the existing arrow
- Move the cue "Space to Grab or Release" down so the new focus rectangle does not occlude the cue dialog
- Make the arrow heads slightly smaller, and rather than having two dashes between the arrows, have 3 dashes
   - Note: this will also change the cueing arrow above the soccer ball since I believe they use the same asset. This is the desired behavior.

**Comment by samreid** [comment]
@catherinecarter agreed this is much better, closing.
