### ISSUE TITLE
Write Implementation.md

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#442]
The Implementation.md file needs to be written for both the soccer-common and center-and-variability repos.

**Comment by samreid** [comment]
I wrote an initial draft, would be good for @marlitas and @matthew-blackman to see what else should be added.

**Comment by samreid** [comment]
After the changes, implementation-notes.md for center-and-variability and soccer-common are looking much better now. @marlitas or @matthew-blackman want to review before we send it over to @pixelzoom?

**Comment by pixelzoom** [comment]
For code review #447 ...

I made some minor changes to center-and-variablility/doc/implementation-notes.md in the above commit.  There are a handful of things that I didn't feel comfortable changing:

---

- [ ] Why is CAVConstants.ts at the end of this sentence?

> which are shown in the accordion box and info dialogs [CAVConstants.ts](../js/common/CAVConstants.ts).

---

- [ ] This is probably no longer true based on changes in https://github.com/phetsims/center-and-variability/issues/463. Do you want to instead say something about `isDisposable: false`?

> **dispose**: A lint rule prevents the usage of the term dispose in this repo, disposal is not supported and should not be used.

---

- [ ] There's a singular/plural problem here, but I'm not sure which word to adjust:

> Likewise, intervalToolDeltaStableProperty works around an inconsistent intermediate values.

---

- [ ] I couldn’t immediately find the “context option” mentioned here. Could you be specific here?

> The Variability Measurements (range, MAD, IQR) have subtle variations when shown in the accordion box vs in the info dialog. This is managed with a context option.

**Comment by pixelzoom** [comment]
For code review #447 ...

Minor fixes in the above commit.

And a few things I didn't feel comfortable changing:

---

- [ ] Same as above:
> dispose: A lint rule prevents the usage of the term dispose in this repo, disposal is not supported and should not be used.

---

- [ ] Should this be deleted? Or language changed to refer to "this repo" instead of "this sim"?
- [ ] 
> The PhET-iO instrumentation of this sim is relatively straightforward. As described
in [Memory Management](#memory-management), everything in this sim is created at startup, and exists for the lifetime of the sim. So there is no sim-specific use of PhetioGroup or PhetioCapsule. See examples.md for examples of how to use the PhET-iO API.

**Comment by marlitas** [comment]
Read over and committed grammar fixes for implementation-notes in CaV.

**Comment by marlitas** [comment]
I addressed all of @pixelzoom's feedback in the above commits. The only one I was not quite sure about was:
`This is not true. SoccerCommonQueryParameters.ts exists.`

I made a separate commit for addressing the language in the query parameter section. I'm not sure if I used the right wording to express how the query parameters are being used.

I also question if both are being used... I saw `slowAnimation` but doesn't `speed=` do exactly what that query parameter is describing?

Over to @samreid  and @matthew-blackman to finish up.

**Comment by samreid** [comment]
`slowAnimation` only slows down the animation for a soccer ball moving up the stack. Very helpful to leave everything else at full speed but just slow down that part. Not sure if we still need it.  If we do, it should get a better name. @matthew-blackman what do you think?

**Comment by matthew-blackman** [comment]
Slow stacking query parameter has been updated in above commit. @pixelzoom over to you for sign-off.

**Comment by pixelzoom** [comment]
I made minor changes and fixes in the above commits, please review.

Remaining problems that I could not address in CAV implementation-notes.md:

- [ ] Refers to `intervalToolDeltaStableProperty`, which does not exist:
 
> Likewise, `intervalToolDeltaStableProperty` works around inconsistent intermediate values.


- [ ] Highly recommended to rename `parentContext` to `representationContext` throughout the implementation, because its type is `RepresentationContext`.  Then update this line in implementaton-notes.md:

> The Variability Measurements (range, MAD, IQR) have subtle variations when shown in the accordion box vs the info dialog. This is managed with a `parentContext` option.

**Comment by marlitas** [comment]
Both of the above points were addressed. I believe this issue is ready to close. Thanks all!
