### ISSUE TITLE
Cards sorting error with shuffled listeners

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#454]
From https://github.com/phetsims/center-and-variability/issues/449 I ran the sim with the query parameter `listenerOrder=random` and noticed that the cards are not behaving properly when the `Sort Data` checkbox is checked. 

<img width="1015" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/7fbc4ec4-3260-4371-81de-02e899d97e6f">

**Comment by samreid** [comment]
I ran 10x times with `listenerOrder=random`, and saw things like "listenerOrder random seed: 52679" reported in the console. However, each time, the data sorted correctly on pressing sort data.  However, slowing time down, I see the problem happens if you have listener order random, and sort data is checked while soccer balls are landing.

**Comment by samreid** [comment]
This commit fixes the problem on my side. @marlitas can you please test/verify/review? Thanks!

**Comment by marlitas** [comment]
This looks fixed from my end. Thanks @samreid!
