### ISSUE TITLE
Excessive coupling to CAVSoccerSceneModel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#494]
For code review #447, similar problem to #492 ...

There is excessive coupling to CAVSoccerSceneModel in the following places:

- [x] InfoValuesNode, IQRInfoValuesNode
- [ ] ~MADInfoNode~
- [ ] ~MediaInfoNode, MedianInfoDialog~
- [x] MedianHighlightLayer
- [ ] ~CardNodeContainer and InteractiveCardNodeContainer~

**Comment by samreid** [comment]
I believe this will raise the same issues as in https://github.com/phetsims/center-and-variability/issues/492. Let's discuss that in this context too.

**Comment by samreid** [comment]
We addressed several of the cases above. For others that we added strikethrough, we believe it is natural and not excessive/problematic to pass the scene model to those views. They need to know several details about the sceneView in order to operate properly. We do not even want to use `Pick` for those cases, unless there is a strong recommendation from the review.  @pixelzoom can you please review and advise?

**Comment by samreid** [comment]
Also, in the commit, we used `Pick` since there is a method accessed on the scene model, and we don't want to have to pass in that instance method separately.

**Comment by pixelzoom** [comment]
👍🏻 closing.
