### ISSUE TITLE
PhET General UI Eraser Sounds

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/center-and-variability#512]
I have a mockup of some eraser sounds so the team can listen and cast their vote. Please view the video here (all sounds are played twice):

[PhET_UI_Eraser_SFX_Mockup.mp4](https://o365coloradoedu.sharepoint.com/:v:/s/PHYS-phet-pilot/Ebux9gk6t1lFnV2p6NTPxJMBkLhweFXiC1PhgB7U45rrMg?e=Qn3KAH)

These are the file names in the video ([the .mp3's are stored here](https://o365coloradoedu.sharepoint.com/:f:/s/PHYS-phet-pilot/Er7Xl3mK2A1AtyKdnPtWTbsBBj4-2PlG40ods4saxSmYyQ?e=KGfCkA))

- EraserSoundRealv2.mp3
- EraserSoundWhoosh.mp3
- EraserSoundMelodyv1.mp3
- EraserSoundMelodyv2.mp3
- EraserSoundMelodyv3.mp3

Edit: I put it in CV because I did not know where else to put this issue.

**Comment by kathy-phet** [comment]
I prefer the whoosh one, among these choices.

**Comment by DianaTavares** [comment]
My favorite is melodyv2, next melodyv3. I don't like it the real sound.

**Comment by catherinecarter** [comment]
My favorites are the whoosh and melodyv2. I agree with Diana that the real sounds don't seem to match. I also think melodyv1 sounds too similar to the reset-all button sound.

**Comment by matthew-blackman** [comment]
+1 for EraserSoundWhoosh

**Comment by kathy-phet** [comment]
My hesitation about Melody 2 was its similarity to the sound we are using for the period divisions in Kepler's Law (when you add more divisions it does this quick trill of the number of divisions you have). Kepler's law doesn't have an eraser, but I do think the trill sound has been used in this context one other time ... so I was hesitant to use it also as an eraser sound since eraser is common across sims. 
https://bayes.colorado.edu/dev/phettest/keplers-laws/keplers-laws_en.html?ea&brand=phet

**Comment by arouinfar** [comment]
I'm also a fan of the whoosh or melody 2, but I don't have any particular preference for one over the other.

> My hesitation about Melody 2 was its similarity to the sound we are using for the period divisions in Kepler's Law (when you add more divisions it does this quick trill of the number of divisions you have)

I agree that there is some similarity between Melody 2 and the sound we are using for the Period Divisions NumberSpinner. I don't think it's similar enough to cause confusion, though. I also don't believe we decided to use that sound for ALL NumberSpinners. The trill pattern works well for a relatively small range, but it won't work in sims with larger ranges like Gas Properties. 

During yesterday's meeting we decided to try a variation of the ResetAllButton sound (which I think is the inspiration for the melody options) because conceptually the eraser button often serves as a mini-reset.

**Comment by DianaTavares** [comment]
During the design meeting of Kepler was shared that the woosh is better. AP share that is not good to have a sound for the eraser as a "mini" reset because it is not completely the case. The erase button is for deleting data.

**Comment by arouinfar** [comment]
Here are some additional notes from the Kepler's Laws design meeting. Attendees were @kathy-phet @arouinfar @AgustinVallejo @ariel-phet @DianaTavares 

Overall we preferred the whoosh, so that is our recommendation for the eraser button. It evokes the idea of clearing something away, which is generally the function of the eraser button. The melodic options sounded a bit too much like the ResetAllButton and NumberSpinner, and we preferred the more distinct sound of the whoosh.

**Comment by amanda-phet** [comment]
I like the whoosh the best!

**Comment by Ashton-Morris** [comment]
Ok I like the whoosh too!

**Comment by samreid** [comment]
Today @catherinecarter @samreid @matthew-blackman agreed we should add the whoosh, based on the considerations above.  @samreid and @matthew-blackman will do so.

**Comment by samreid** [comment]
OK we added the whoosh eraser sound to Center and Variability. I was surprised to see that https://github.com/phetsims/scenery-phet/blob/main/js/buttons/EraserButton.ts doesn't define its own sound in common code (yet?). Anyways this is ready for:
* Listen to the whoosh in context
* Check for balancing
* Comment on whether we need a common code issue to move the sound to common code -- right now it is just in Center and Variability.

**Comment by arouinfar** [comment]
> Comment on whether we need a common code issue to move the sound to common code -- right now it is just in Center and Variability.

Yes, this sound needs to be in common code. Kepler's Laws also uses this button and is in the final sign-off stage for sound. @AgustinVallejo fyi.

**Comment by samreid** [comment]
OK I additionally moved it to scenery-phet/ so other sims can use it.  Based on discussion with @pixelzoom @AgustinVallejo and myself, we did not yet "bake it in" to EraserButton, but EraserButtons that want it can opt-in to it and use the common code sound.

**Comment by samreid** [comment]
> balancing sounds pretty good to me. If anything, the eraser sounds slightly quieter than the reset all, but perhaps negligible

@catherinecarter want me to boost the volume on the eraser before closing? Please mention a proposed percent increase if you want me to adjust that.

**Comment by catherinecarter** [comment]
I'm not sure the impact of 1%, so it's hard to assess, but maybe try 10%?

**Comment by samreid** [comment]
OK I increased it by 10% (just for CaV).

**Comment by pixelzoom** [comment]
> Based on discussion with @pixelzoom @AgustinVallejo and myself, we did not yet "bake it in" to EraserButton, but EraserButtons that want it can opt-in to it and use the common code sound.

For the record, my preference was to make this the default sound for EraserButton ("bake it in").  I suspect that it's appropriate for most (perhaps all) usages of EraserButton. And developers will either forget, or not know, to opt in.  The decision to not make it the default sound was based on a desire to defer the work involved in doing so: discussing with designers, determining whether the sound is relevant to all usages of EraserButton, opting out in cases where it's not appropriate,...

So... I'm fine with deferring for now. But I'd like to see a scenery-phet issue for making this the default sound.

**Comment by kathy-phet** [comment]
@samreid - I agree that making this the default UI sound seems like the right path forward here. We had a quorum of designers weigh in on this sound across contexts and so I think its a good default, and should be enabled when UI sound is enabled in general. With an opt-out or replace, rather than an opt-in policy.

**Comment by samreid** [comment]
Sounds good, I investigated and opened https://github.com/phetsims/scenery-phet/issues/818 when I ran into trouble. We will close this issue after the center-and-variability-specific volume is finalized.

**Comment by Ashton-Morris** [comment]
The volume level in CAV is very spot on. I do think this should be default also, and I think the current volume in CAV should be the level its put in at.

**Comment by catherinecarter** [comment]
Sounds great! Thanks!

**Comment by samreid** [comment]
Thanks, I'll close this and continue in https://github.com/phetsims/scenery-phet/issues/818
