### ISSUE TITLE
Cueing arrows don't disappear until you switch keyboard focus to a new card/soccer ball 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#529]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/976, on the Median screen, if I grab and move a card with keyboard nav, the cueing arrows will disappear once movement begins. However if I tab away and then tab back (or release and then grab again), the cueing arrows will reappear. They only disappear if I move focus to a different card. 

This same issue happens with the soccer balls on all three screens. 

**Steps to reproduce**
For the Cards:
1. On the median screen, tab to and press the Kick 5 button
2. Tab to the cards. Grab and move a card.
3. Press space to release --cueing arrows reappear
4. Grab the same card and move it again
5. Press tab and then shift+tab to return to the card --cueing arrows will be there

*follow similar steps with a soccer ball on any screen

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/1feb0f34-b970-45b0-bd67-f10370753106

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.1.0-dev.14/phet/center-and-variability_all_phet.html
Version: 1.1.0-dev.14 2023-09-01 18:18:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1317x716
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by catherinecarter** [comment]
I don't believe this is a bug, but I can see how this is confusing. The arrows are identical, and once you pick a ball/card up and move it, it's strange to have the arrow still there if the user hasn't changed stacks or cards. There are two cues, each indicating something different but this is not clear. 

One cue is to press space to pick up or release, the other cue is the arrow to move stacks of soccer balls or between cards, without picking a ball or card up. It's unclear these two cues mean to take different actions. 

I propose this, and I would love to hear @terracoda's voice here. 

Since the arrows to cue moving between stacks/cards and to move a ball/card look identical, would it make sense to either:
1. show the arrow when tabbing, and if a ball is picked up, do not show another arrow to indicate a ball/card can be moved
2. only show the arrow after the space bar or enter has been pressed

It is confusing to have the same arrow indicate two different interactions. I'd be ok with either of the above, although option 2 seems to make more sense since the right/left action to move between items in a group is indicated in the keyboard dialog. I'm also open to other suggestions.

**Comment by marlitas** [comment]
I have a third possible option...

What if we only show the arrow (no hand) before the ball is grabbed to indicate that you can select a different ball, and then add the hand when a user picks up a ball to indicate that you can move it as well?

**Comment by catherinecarter** [comment]
I hesitate to do that since (it's my understanding, could be wrong) that with alt-input, arrows are the standard cue. The hand indicates you can touch it, but the user isn't using touch. 

I'd worry the user would think you'd have to touch the ball to move it rather than being able to use the keyboard. I'm also concerned the hand and the focus rectangle would occlude each other. The focus is always z-ordered on top, so the hand might be hard to see/identify as a hand.

**Comment by terracoda** [comment]
Using arrow keys to move to a different stack is a basic navigation action for moving to an item in a group.

I would try what Cathy suggested, no arrow cue until the ball is grabbed.

Btw, will there be any more interviews on this sim? I know the timeline is tight already.

**Comment by catherinecarter** [comment]
Thanks, @terracoda, we will take the first arrow out and only have an arrow appear upon pressing space to grab the ball/card. 

I don't have any interviews scheduled at the moment prior to publishing. We are near publishing (yay!).

**Comment by marlitas** [comment]
The keyboard select cue arrow has been removed. Over to @catherinecarter and @matthew-blackman for review.

**Comment by catherinecarter** [comment]
Looks great in the soccer ball area. It is still there on the cards. @marlitas, can we remove the first cueing hand on the cards as well? Thanks!

**Comment by marlitas** [comment]
oops! Got it. I always forget about one or the other lol. Over to you for that final check @catherinecarter.

**Comment by catherinecarter** [comment]
Looks great! :)

**Comment by matthew-blackman** [comment]
Commits look good and are relatively straightforward. They also cleaned up a few files. Nice work @marlitas! Closing
