### ISSUE TITLE
pan/zoom very slow on Variability screen 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#530]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/976 and possibly related to https://github.com/phetsims/center-and-variability/issues/527:
On the Variability screen, panning is very slow when tabbing through the controls while zoomed in. I do not see this issue with mac + chrome. 

**Steps to reproduce**
1. With Safari, on the Variability screen zoom in
2. Tab through the controls so that the screen pans.

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/ac7b2ba7-2f01-4929-95af-0eb89c38fc53

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.1.0-dev.14/phet/center-and-variability_all_phet.html
Version: 1.1.0-dev.14 2023-09-01 18:18:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language: en-US
Window: 1303x724
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
I'm not familiar with the implementation of pan/zoom, so I'm afraid that I don't have anything to offer here. Let's involve @jessegreenberg.

**Comment by pixelzoom** [comment]
If we find that there's a general problem that's affecting performance, please create an issue in the appropriate common-code repo.

**Comment by jessegreenberg** [comment]
I confirmed that panning animation is very slow on Safari on the Variability screen, for all forms of input.  I do think this is related to #527.  I did a little poking around in the sim and found that removing the `frontLayerToggleNode` from CAVScreenView fixes this issue and #527.

Just brainstorming - instead of ToggleNode for scene visibility, only keeping the selected scene in the scene graph might be better for performance. Though then changing scenes might be a bit slower.

Or maybe there is another optimization in the scenes themselves.

**Comment by marlitas** [comment]
I agree a solution to https://github.com/phetsims/center-and-variability/issues/527 will be the solution to this problem. I'm not quite sure what the best approach to fixing the performance issues for the third screen is... Adding and removing children to the scene graph sounds like it could start becoming complex when working with phet-io state. I can just imagine incorrect intermediary problems cropping up in annoying ways... 

I would like to discuss the best approach with other devs.

**Comment by jessegreenberg** [comment]
Knowing that the `frontLayerToggleNode` is the culprit and only has the `frontSceneLayer` of each scene view might show us a way to make it faster. I think that front layer is just the soccer ball nodes and kickers?  I am wondering now if this started happening when the new character sets were added. Would it be more performant to only have the used kicker in the scene graph instead of toggling visibility?

**Comment by samreid** [comment]
Great idea @jessegreenberg. @marlitas and I discussed it and tested it, and we want to change the implementation of the Variability screen so that each scene just has one SoccerPlayerNode that is used for all the kicks. At the moment, it is instantiating 120 SoccerPlayerNodes (for the USA portrayal), and it only needs to create 4.

**Comment by matthew-blackman** [comment]
@marlitas and I worked on this and were able to set the Variability screen to have a only one Kicker and only one KickerNode. Screens 1 and 2 look great, and the Variability screen has one remaining problem that we'll continue in a separate issue.

Do you mind reviewing the commit @samreid ?

**Comment by samreid** [comment]
For the design, was it decided we want to continue showing the kicker even when all the balls have been kicked?  Also, this callback in SoccerSceneModel no longer uses `maxKicks`. I can't tell if it is an oversight, or maybe if `maxKicksProperty` should no longer be a dependency.

```ts
    Multilink.multilink( [ this.activeKickIndexProperty, this.maxKicksProperty ], ( activeKickIndex, maxKicks ) => {
      this.kickers.forEach( ( kicker, index ) => {
        kicker.kickerPhaseProperty.value = ( options.isSingleKickerScene || index === activeKickIndex ) ? KickerPhase.READY : KickerPhase.INACTIVE;
      } );
    } );
```

Everything else looks great, nice work! Very snappy.

**Comment by marlitas** [comment]
> For the design, was it decided we want to continue showing the kicker even when all the balls have been kicked?

In the third screen yes.

>  I can't tell if it is an oversight, or maybe if maxKicksProperty should no longer be a dependency.

Oops! Thanks for catching that. We needed to still include the maxKicks logic in the ternary. fixed in the above commit.

**Comment by samreid** [comment]
Code change looks sensible and it looks OK in my testing, thanks.  Back to @marlitas and @matthew-blackman to see if there's anything else.

**Comment by marlitas** [comment]
Great. Let me send this over to @Nancy-Salpepi, but if she confirms all looks well we can close!

**Comment by Nancy-Salpepi** [comment]
Looks great on main! Closing!
