### ISSUE TITLE
Cueing hand/arrows should appear in Standard PhET-iO wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#532]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/976, if an instructional designer moves a ball in studio, the Standard PhET-iO wrapper won't have the hand/cueing arrows over the ball once all the balls are kicked. This happens on all screens. 

Also, if a designer moves a card on the Median screen, when the sim is launched there won't be a cueing arrow until another ball is kicked. I'm not sure if this was intentional or not.

**Steps to reproduce**
1. On the Median screen, press the Kick 5 button
2. Move a soccer ball and a card
3. Press Test
4. In the Standard PhET-iO wrapper press the Kick 5 button 2 more times

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/394b72c1-9511-406d-9641-b5320f5b4bce

**Comment by catherinecarter** [comment]
I believe it was intentional. The instructional designer can set the location of every ball, creating a distribution where the cueing hand/arrow appear upon the last kick. 

I'm glad you brought that up, though, because the instructional designer can do two things to force the hand to appear: 
1. they can re-set `centerAndVariability.medianScreen.model.soccerArea.soccerBallDragIndicatorModel.soccerBallHasBeenDraggedProperty` to false after they move a ball. This will tell the sim a ball has not moved, and hence, the hand/arrow will appear
2. they can set `centerAndVariability.medianScreen.model.soccerArea.soccerBallDragIndicatorModel.isDragIndicatorVisibleProperty` to `true` to force it to appear, and then move the cue to their desired location with `centerAndVariability.medianScreen.model.soccerArea.soccerBallDragIndicatorModel.valueProperty`. 

I will double check these options are in the examples document and clear to the user. Thank you!

**Comment by Nancy-Salpepi** [comment]
Ah I see it in the examples doc. Thanks @catherinecarter! I think this can be closed then.

**Comment by Nancy-Salpepi** [comment]
Actually @catherinecarter I'm going to reopen this. I see you only have examples for the variability screen listed in the examples doc (take note that the examples need to be fixed https://github.com/phetsims/center-and-variability/issues/535). How about the other screens?

**Comment by catherinecarter** [comment]
Yes, thanks. I actually updated it already and reordered them to be grouped by `visibleProperty` and `valueProperty` separately. I did this for each screen.
https://github.com/phetsims/phet-io-sim-specific/blob/main/repos/center-and-variability/examples.md

**Comment by Nancy-Salpepi** [comment]
All the phet-io IDs look good! I would just make that one change to the directions and then close this issue....again!

Once a ball has been dragged, the cueing hand will not appear, even after the last kick. To make the cueing hand appear, reset the model by changing the `soccerBallHasBeenDragged` property to false. The cueing hand will appear upon the last kick.

**Comment by Nancy-Salpepi** [comment]
One last question here @catherinecarter, if a designer moves a card, how can we get the cueing/hand arrow back in the launched sim?

**Comment by catherinecarter** [comment]
@Nancy-Salpepi, currently it is not possible to force the hand to reappear on the cards. It turned out to be pretty complicated to implement, so we decided to encourage instructional designers to do one of two things: 
- use the `kickDistributionStrategy` of `distanceByIndex` to create a set distribution, and hence, a specific order of cards if they want to put the cards in a particular order and have the hand appear with the cards in that order (since the hand appears on the 2nd kick and stays until a card has been moved)
- move a ball rather than a card if the card order is to be changed, since the hand/arrow on the balls can be made to reappear if a ball is moved

I'll double check to see if that's clear in the examples.md doc and add it if not.

**Comment by Nancy-Salpepi** [comment]
Thanks for the explanation @catherinecarter!

**Comment by Nancy-Salpepi** [comment]
Closed this by mistake.

**Comment by Nancy-Salpepi** [comment]
@catherinecarter the update in the examples.md looks great!
Based on our slack discussion, I created another [issue](https://github.com/phetsims/center-and-variability/issues/541) for the Card cueing hand behavior.
Is there anything left to do here?

**Comment by catherinecarter** [comment]
Thanks, @Nancy-Salpepi!

I think we're good for this issue, and thanks for making the other one :)

**Comment by catherinecarter** [comment]
Closing.
