### ISSUE TITLE
Blue mouths

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#552]
While working on #523 I noticed that a couple of the kickers had blue mouths in their kicking pose.

Might be good to double check others as well.
<img width="118" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/56b2d24c-5fa8-4a8e-9fd5-c3399858b345">
<img width="95" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/f4d6a926-f2b5-4993-9ade-73982f332c7e">

**Comment by catherinecarter** [comment]
Nice catch! I will look at the other kickers and upload new images if I find any. Yikes!

**Comment by catherinecarter** [comment]
I uploaded new image files for those two characters in soccer-common. I didn't see any other characters other than the ones you found, so that's good. 

What happened is that their mouths had a transparent background rather than white, but since the artboard was white, I couldn't tell before exporting. 

Hopefully all is well now. Thanks for noticing that!

**Comment by marlitas** [comment]
This issue is good to go thanks @catherinecarter!
