### ISSUE TITLE
Dragging soccer ball to the edge of the screen may not pan

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#88]
**Device**
iPad
**OS**
iPadOS 15
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/qa/issues/781
When zoomed in, dragging the soccer ball to the edge of the screen may or may not pan the screen. If it does pan it may only move one tick.
**Visuals**

https://user-images.githubusercontent.com/41024075/157323463-7aceb7e1-1648-470c-be8e-3ac5caf04568.MOV

**Comment by amanda-phet** [comment]
This seems like an issue because the balls snap to the tick marks, and we probably don't want to chance the snappiness of that interaction. It sounds like this might be a tough one for @chrisklus and @samreid .

**Comment by samreid** [comment]
Also tagging @jessegreenberg in case he knows a good solution for this.

**Comment by jessegreenberg** [comment]
This is happening because at the edge of the screen the Pointer doesn't have enough space to drag more than half way between tick marks to pull the CASObjectNode to a new position. A function was added to DragListener just this week that can fix this. By telling the AnimatedPanZoomListener to increase the bounds to keep in view we can ensure that the Pointer will always have enough space to drag the Node to a new position.

@chrisklus @samreid can you please review this commit? https://github.com/phetsims/center-and-spread/commit/b52f65e8aa7f490e75c43bf00cc282368a9d5776

**Comment by samreid** [comment]
The commit makes sense and it seems to be working well in my testing. @KatieWoe would you please verify on master/phettest?

**Comment by KatieWoe** [comment]
This seems a lot better on master. It still seemed to get caught occasionally, but it was much easier to resolve and happened much less.

**Comment by samreid** [comment]
That sounds good to me, I found as I held an object near the edge, if it caught, I moved it vertically and it resolved. I feel I have seen this pattern in other UIs before too.  I feel this can be closed.
